### ISSUE TITLE
Logging with dictConfig won't work with python 2.6

### ISSUE THREAD

**Issue by raphdg** [SeyZ/baboon#23]

**Comment by SeyZ** [comment]
Maybe I can use the following project:

https://bitbucket.org/vinay.sajip/dictconfig

For example, take a look at:

http://www.calazan.com/how-to-configure-the-logging-module-using-dictionaries-in-python-2-6/

**Comment by SeyZ** [comment]
Fixed with the dictconfig thirdparty class.
