### ISSUE TITLE
Expansion of documentation

### ISSUE THREAD

**Issue by rvanlaar** [SeyZ/baboon#68]
I'm missing information about how the communication flows with baboon and how the whole project is notififed.

Could you please add this and eloborate on how xmpp is used.

**Comment by SeyZ** [comment]
Yeah sure, I will be write some wikis to explain how Baboon is architectured. In addition, I need to write another wiki to explain how to host your Baboon server if wanted.

**Comment by rvanlaar** [comment]
Thanks for the swift reply. I heard about baboon because of one of the FOSDEM talks :+1:

**Comment by SeyZ** [comment]
Oh great :-) Fosdem was so cool!

I created a wiki page. Is it clearer? https://github.com/SeyZ/baboon/wiki/Baboon's-architecture
